### PR TITLE
Add support for long int in class Value.

### PR DESCRIPTION
**Pull request by olivier-stasse**
Add support for long int.

### CODE REVIEW

**Review by MaximilienNaveau — APPROVED** [review]
Hi,
the code itself is good we can merge this PR.

I however do not understand the need of it as now you can create command with boost-python directly and hence have access to virtually any function signature.
Hence the need of such development is minimal, or I am missing something...

You can still merge the request. It seems a good idea to be able to share `long int` through commands.

**Comment by olivier-stasse** [comment]
> Hi, the code itself is good we can merge this PR.
> 
> I however do not understand the need of it as now you can create command with boost-python directly and hence have access to virtually any function signature. Hence the need of such development is minimal, or I am missing something...
> 
> You can still merge the request. It seems a good idea to be able to share `long int` through commands.
I agree. 
For now let us say this is mostly to maintain existing code using command.
The current problem is that many compiling warnings are popping up because not all types are available through the Value interface.

**Comment by olivier-stasse** [comment]
One note: people used to command appreciate the fact that they do not have to do the python bindings.
If we bind other language and use an equivalent system, then this would be handy.

**Comment by MaximilienNaveau** [comment]
Agreed, good point!

**Review by nim65s — APPROVED** [review]

**Pull request merged**
